### ISSUE TITLE
libbtstack.so: cannot open shared object file

### ISSUE THREAD

**Issue by mrsec-dev** [Matheus-Garbelini/esp32_bluetooth_classic_sniffer#1]
Hi there,

got some issues running BTSnifferBREDR. 
Any hint?

Parrot OS

Best regards

─[root@deadbeef-24296hg]─[/home/deadbeef/EagleEye/esp32_bluetooth_classic_sniffer]
└──╼ #./BTSnifferBREDR.py --port /dev/ttyUSB0 --live-wireshark
Using options:
        Serial Port: /dev/ttyUSB0
        Serial Baud: 921600
        BT Host Program: ./host_stack/spp_counter
        Host BDAddress: e0:d4:e8:19:c7:68
        Target BDAddress: None
[Sniffer] [!] Starting Wireshark...
16:23:58.530     Main Warn QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[!] Reset Done! EN pin toggled HIGH->LOW->HIGH
[!] Waiting 0.8s...
[ESP32BT] Firmware version: 1.4.1
sh: 1: setserial: not found
HCI Bridge started on /dev/pts/2
ESP32BT driver started on /dev/ttyUSB0@921600
Starting ['./host_stack/spp_counter', '-u', '/dev/pts/2', '-a', 'None']
./host_stack/spp_counter: **error while loading shared libraries: libbtstack.so: cannot open shared object file: No such file or directory**

**Comment by AleshR** [comment]
Hi! I found solution, you need manually copy libbtstack.so to /usr/lib/.

Use following commands (in esp32_bluetooth_classic_sniffer folder):
cp host_stack/libbtstack.so /usr/lib/

This works for me :)

**Comment by Matheus-Garbelini** [comment]
Hi, I just updated the repo to fix this issue.
